# Generated by Django 4.1.2 on 2023-06-02 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'district',
                'verbose_name_plural': 'districts',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
                ('city', models.CharField(max_length=150)),
                ('open', models.BooleanField(default=True)),
                ('main_image', models.ImageField(blank=True, upload_to='main_image')),
                ('sub_img1', models.ImageField(blank=True, upload_to='media')),
                ('sub_img2', models.ImageField(blank=True, upload_to='media')),
                ('sub_img3', models.ImageField(blank=True, upload_to='media')),
                ('sub_img4', models.ImageField(blank=True, upload_to='media')),
                ('location', models.TextField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.district')),
            ],
            options={
                'verbose_name': 'place',
                'verbose_name_plural': 'places',
                'ordering': ('name',),
            },
        ),
    ]
