# Generated by Django 4.1.2 on 2023-06-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_alter_place_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='main_image',
        ),
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
