# Generated by Django 4.1.2 on 2023-06-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_alter_place_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='image',
            new_name='image1',
        ),
        migrations.RemoveField(
            model_name='place',
            name='sub_img1',
        ),
        migrations.RemoveField(
            model_name='place',
            name='sub_img2',
        ),
        migrations.RemoveField(
            model_name='place',
            name='sub_img3',
        ),
        migrations.RemoveField(
            model_name='place',
            name='sub_img4',
        ),
        migrations.AddField(
            model_name='place',
            name='image2',
            field=models.ImageField(blank=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='place',
            name='image3',
            field=models.ImageField(blank=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='place',
            name='image4',
            field=models.ImageField(blank=True, upload_to='gallery'),
        ),
    ]
