# Generated by Django 4.1.2 on 2023-06-06 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
