# Generated by Django 4.1.2 on 2023-06-07 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
