# Generated by Django 4.1.2 on 2023-06-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0014_remove_comments_cplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='cuser',
            field=models.CharField(max_length=100),
        ),
    ]
