# Generated by Django 4.1.2 on 2023-06-07 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0015_alter_comments_cuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
