# Generated by Django 4.1.2 on 2023-06-07 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0016_delete_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctext', models.TextField(blank=True)),
                ('cimage', models.ImageField(blank=True, upload_to='comment')),
                ('cuser', models.CharField(max_length=100)),
                ('cplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.place')),
            ],
        ),
    ]
