# Generated by Django 4.1.2 on 2023-06-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0019_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='uploaded')),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
