# Generated by Django 4.1.2 on 2023-06-08 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0020_parameter_delete_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parameter',
        ),
    ]
