# Generated by Django 4.1.2 on 2023-06-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0026_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='cimage',
            field=models.ImageField(blank=True, null=True, upload_to='cimage'),
        ),
    ]
