# Generated by Django 4.1.2 on 2023-06-17 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0027_comments_cimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='ctext',
        ),
    ]
