# Generated by Django 4.1.2 on 2023-06-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0030_comments_cdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='cdate',
            field=models.DateField(auto_now=True),
        ),
    ]
